#!/bin/bash

PERF=${PERF:-"perf"}
EVDIR=${EVDIR:-"tools/perf/pmu-events/arch/powerpc"}
LOG="ppc-tests.log"
OPTS="--output $LOG --append"

> $LOG

#
# Test 1: Run through all Power8 events.
#
list=`grep -r EventName $EVDIR | awk -F: '{print $3}' | awk -F\" '{print $2}'`

echo ============ Test 1 ============ >> $LOG
for e in $list
do

	echo "perf stat -e $e sleep 0.1" >> $LOG

	$PERF stat $OPTS -e $e sleep 0.01
	if [ $? -ne 0 ]; then
		echo "Was $PERF binary built with JSON support?"
		exit 1;
	fi
done

#
# Test 2: Specify same event using its generic name, json name and raw code
#	  and dump the event attributes
#

echo ============ Test 2 ============ >> $LOG

$PERF stat $OPTS -vv -e cycles,r1e,PM_CYC sleep 1 >> $LOG 2>&1

#
# Test 3: Test lower and mixed-case event names for JSON events
#

echo ============ Test 3 ============ >> $LOG
echo $PERF stat $OPTS -e pm_1plus_ppc_cmpl,pm_run_inst_cmpl,pM_br_2PaTh sleep 1 >> $LOG

$PERF stat $OPTS -e pm_1plus_ppc_cmpl,pm_run_inst_cmpl,pM_br_2PaTh sleep 1

#
# Test 4: List powerpc JSON events without description
#

echo ============ Test 4 ============ >> $LOG
echo $PERF list --no-desc json >> $LOG
$PERF list --no-desc json >> $LOG 2>&1
